#############################################################################
# Makefile for building: .\calculator.js
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  ..\calculator\calculator.pro
# Template: app
# Command: C:\Qt\5.15.0\wasm_32\bin\qmake.exe -o Makefile ..\calculator\calculator.pro -spec wasm-emscripten "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -g -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -g -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra $(DEFINES)
INCPATH       = -I..\calculator -I. -IC:\Qt\5.15.0\wasm_32\include -IC:\Qt\5.15.0\wasm_32\include\QtWidgets -IC:\Qt\5.15.0\wasm_32\include\QtGui -IC:\Qt\5.15.0\wasm_32\include\QtCore -I. -I/.emscripten_ports/openssl/include -IC:\Qt\5.15.0\wasm_32\mkspecs\wasm-emscripten
QMAKE         = C:\Qt\5.15.0\wasm_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.15.0\wasm_32\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.15.0\wasm_32\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = calculator.js1.0.0
DISTDIR = C:\Qt\Examples\Qt-5.15.0\widgets\widgets\build-calculator-Qt_5_15_0_WebAssembly-Debug\.tmp\calculator.js1.0.0
LINK          = em++
LFLAGS        = -s WASM=1 -s FULL_ES2=1 -s FULL_ES3=1 -s USE_WEBGL2=1 -s EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=["UTF16ToString","stringToUTF16"] --bind -s FETCH=1 -g -s WASM=1 -s FULL_ES2=1 -s FULL_ES3=1 -s USE_WEBGL2=1 -s EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=["UTF16ToString","stringToUTF16"] --bind -s FETCH=1 -s ASSERTIONS=2 -s DEMANGLE_SUPPORT=1 -s GL_DEBUG=1 -s ALLOW_MEMORY_GROWTH=1 --source-map-base http://localhost:8000/
LIBS          = $(SUBLIBS) C:/Qt/5.15.0/wasm_32/plugins/platforms/libqwasm.a C:/Qt/5.15.0/wasm_32/lib/libQt5EventDispatcherSupport.a C:/Qt/5.15.0/wasm_32/lib/libQt5FontDatabaseSupport.a C:/Qt/5.15.0/wasm_32/lib/libqtfreetype.a C:/Qt/5.15.0/wasm_32/lib/libQt5EglSupport.a C:/Qt/5.15.0/wasm_32/plugins/imageformats/libqgif.a C:/Qt/5.15.0/wasm_32/plugins/imageformats/libqicns.a C:/Qt/5.15.0/wasm_32/plugins/imageformats/libqico.a C:/Qt/5.15.0/wasm_32/plugins/imageformats/libqjpeg.a C:/Qt/5.15.0/wasm_32/plugins/imageformats/libqtga.a C:/Qt/5.15.0/wasm_32/plugins/imageformats/libqtiff.a C:/Qt/5.15.0/wasm_32/plugins/imageformats/libqwbmp.a C:/Qt/5.15.0/wasm_32/plugins/imageformats/libqwebp.a C:/Qt/5.15.0/wasm_32/lib/libQt5Widgets.a C:/Qt/5.15.0/wasm_32/lib/libQt5Gui.a C:/Qt/5.15.0/wasm_32/lib/libqtlibpng.a C:/Qt/5.15.0/wasm_32/lib/libqtharfbuzz.a C:/Qt/5.15.0/wasm_32/lib/libQt5Core.a C:/Qt/5.15.0/wasm_32/lib/libqtpcre2.a   
AR            = emar cqs
RANLIB        = 
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ..\calculator\button.cpp \
		..\calculator\calculator.cpp \
		..\calculator\main.cpp C:/Qt/Examples/Qt-5.15.0/widgets/widgets/build-calculator-Qt_5_15_0_WebAssembly-Debug/calculator.js_plugin_import.cpp \
		moc_button.cpp \
		moc_calculator.cpp
OBJECTS       = button.obj \
		calculator.obj \
		main.obj \
		calculator.js_plugin_import.obj \
		moc_button.obj \
		moc_calculator.obj
DIST          =  ..\calculator\button.h \
		..\calculator\calculator.h ..\calculator\button.cpp \
		..\calculator\calculator.cpp \
		..\calculator\main.cpp
QMAKE_TARGET  = calculator.js
DESTDIR       = .\\
TARGET        = .\calculator.js


first: all
####### Build rules

.\calculator.js: C:\Qt\5.15.0\wasm_32\lib\libQt5Widgets.a C:\Qt\5.15.0\wasm_32\lib\libQt5Gui.a C:\Qt\5.15.0\wasm_32\lib\libQt5Core.a $(OBJECTS)  apphtml appjs appsvg
	@if not exist .\ mkdir .\ & if not exist .\ exit 1
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ..\calculator\calculator.pro C:\Qt\5.15.0\wasm_32\mkspecs\wasm-emscripten\qmake.conf C:\Qt\5.15.0\wasm_32\mkspecs\features\spec_pre.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\common\sanitize.conf \
		C:\Qt\5.15.0\wasm_32\mkspecs\common\gcc-base.conf \
		C:\Qt\5.15.0\wasm_32\mkspecs\common\clang.conf \
		C:\Qt\5.15.0\wasm_32\mkspecs\qdevice.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\device_config.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\wasm\emcc_ver.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\qconfig.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmlmodels.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_service_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_eglvideonode.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qgif.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qicns.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qico.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qjpeg.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qsvg.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qsvgicon.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtga.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtiff.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtsensors_generic.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qwasm.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qwbmp.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qwebp.pri \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\qt_functions.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\qt_config.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\wasm-emscripten\qmake.conf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\spec_post.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\toolchain.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\default_pre.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\wasm\default_pre.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\resolve_config.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\default_post.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\qml_debug.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\wasm\wasm.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\warn_on.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\qt.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\resources_functions.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\resources.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\moc.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\unix\opengl.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\uic.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\qmake_use.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\file_copies.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\exceptions.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\yacc.prf \
		C:\Qt\5.15.0\wasm_32\mkspecs\features\lex.prf \
		..\calculator\calculator.pro \
		C:\Qt\5.15.0\wasm_32\plugins\platforms\libqwasm.prl \
		C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqgif.prl \
		C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqicns.prl \
		C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqico.prl \
		C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqjpeg.prl \
		C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqtga.prl \
		C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqtiff.prl \
		C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqwbmp.prl \
		C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqwebp.prl \
		C:\Qt\5.15.0\wasm_32\lib\libQt5Widgets.prl \
		C:\Qt\5.15.0\wasm_32\lib\libQt5Gui.prl \
		C:\Qt\5.15.0\wasm_32\lib\libQt5Core.prl
	$(QMAKE) -o Makefile ..\calculator\calculator.pro -spec wasm-emscripten "CONFIG+=debug" "CONFIG+=qml_debug"
C:\Qt\5.15.0\wasm_32\mkspecs\features\spec_pre.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\common\sanitize.conf:
C:\Qt\5.15.0\wasm_32\mkspecs\common\gcc-base.conf:
C:\Qt\5.15.0\wasm_32\mkspecs\common\clang.conf:
C:\Qt\5.15.0\wasm_32\mkspecs\qdevice.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\features\device_config.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\wasm\emcc_ver.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\qconfig.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmlmodels.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmlmodels_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_service_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_texttospeech.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_eglvideonode.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qgif.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qicns.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qico.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qjpeg.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qsvg.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qsvgicon.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtga.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtiff.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtsensors_generic.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qwasm.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qwbmp.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\modules\qt_plugin_qwebp.pri:
C:\Qt\5.15.0\wasm_32\mkspecs\features\qt_functions.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\qt_config.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\wasm-emscripten\qmake.conf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\spec_post.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\toolchain.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\default_pre.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\wasm\default_pre.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\resolve_config.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\default_post.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\qml_debug.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\wasm\wasm.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\warn_on.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\qt.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\resources_functions.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\resources.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\moc.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\unix\opengl.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\uic.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\qmake_use.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\file_copies.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\testcase_targets.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\exceptions.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\yacc.prf:
C:\Qt\5.15.0\wasm_32\mkspecs\features\lex.prf:
..\calculator\calculator.pro:
C:\Qt\5.15.0\wasm_32\plugins\platforms\libqwasm.prl:
C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqgif.prl:
C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqicns.prl:
C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqico.prl:
C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqjpeg.prl:
C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqtga.prl:
C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqtiff.prl:
C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqwbmp.prl:
C:\Qt\5.15.0\wasm_32\plugins\imageformats\libqwebp.prl:
C:\Qt\5.15.0\wasm_32\lib\libQt5Widgets.prl:
C:\Qt\5.15.0\wasm_32\lib\libQt5Gui.prl:
C:\Qt\5.15.0\wasm_32\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ..\calculator\calculator.pro -spec wasm-emscripten "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE


all: Makefile .\calculator.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents C:\Qt\5.15.0\wasm_32\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents ..\calculator\button.h ..\calculator\calculator.h $(DISTDIR)\
	$(COPY_FILE) --parents ..\calculator\button.cpp ..\calculator\calculator.cpp ..\calculator\main.cpp $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm C:/Qt/Examples/Qt-5.15.0/widgets/widgets/build-calculator-Qt_5_15_0_WebAssembly-Debug/calculator.js_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: C:/Qt/5.15.0/wasm_32/plugins/platforms/wasm_shell.html
	$(QMAKE) -install sed -e s/@APPNAME@/calculator/g C:/Qt/5.15.0/wasm_32/plugins/platforms/wasm_shell.html > C:/Qt/Examples/Qt-5.15.0/widgets/widgets/build-calculator-Qt_5_15_0_WebAssembly-Debug/calculator.html

appjs: C:/Qt/5.15.0/wasm_32/plugins/platforms/qtloader.js
	copy /y C:\Qt\5.15.0\wasm_32\plugins\platforms\qtloader.js C:\Qt\Examples\Qt-5.15.0\widgets\widgets\build-calculator-Qt_5_15_0_WebAssembly-Debug

appsvg: C:/Qt/5.15.0/wasm_32/plugins/platforms/qtlogo.svg
	copy /y C:\Qt\5.15.0\wasm_32\plugins\platforms\qtlogo.svg C:\Qt\Examples\Qt-5.15.0\widgets\widgets\build-calculator-Qt_5_15_0_WebAssembly-Debug

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) calculator.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: C:\Qt\5.15.0\wasm_32\mkspecs\features\data\dummy.cpp
	em++ -g -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra -dM -E -o moc_predefs.h C:\Qt\5.15.0\wasm_32\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all: moc_button.cpp moc_calculator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_button.cpp moc_calculator.cpp
moc_button.cpp: ..\calculator\button.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\QToolButton \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtoolbutton.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtguiglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtcore-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsystemdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qprocessordetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtypeinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsysinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlogging.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qflags.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbasicatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qgenericatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobalstatic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmutex.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnumeric.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qversiontagging.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtgui-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgets-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qabstractbutton.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qicon.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsize.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnamespace.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmargins.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiterator.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrefcount.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qarraydata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhashfunctions.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstring.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qchar.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringliteral.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringview.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringbuilder.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpair.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvector.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainertools_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpoint.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearraylist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qregexp.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringmatcher.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpaintdevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs_win.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrect.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcolor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgb.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgba64.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qshareddata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhash.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcoreevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qscopedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmetatype.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qimage.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixelformat.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtransform.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qmatrix.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpolygon.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qregion.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdatastream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiodevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qline.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qkeysequence.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qwidget.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpalette.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qbrush.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfont.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontmetrics.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qsizepolicy.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcursor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvariant.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdebug.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtextstream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlocale.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qset.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontiguouscache.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurlquery.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfile.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfiledevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qvector2d.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtouchdevice.h \
		moc_predefs.h \
		C:\Qt\5.15.0\wasm_32\bin\moc.exe
	C:\Qt\5.15.0\wasm_32\bin\moc.exe $(DEFINES) --include C:/Qt/Examples/Qt-5.15.0/widgets/widgets/build-calculator-Qt_5_15_0_WebAssembly-Debug/moc_predefs.h -IC:/Qt/5.15.0/wasm_32/mkspecs/wasm-emscripten -IC:/Qt/Examples/Qt-5.15.0/widgets/widgets/calculator -IC:/Qt/5.15.0/wasm_32/include -IC:/Qt/5.15.0/wasm_32/include/QtWidgets -IC:/Qt/5.15.0/wasm_32/include/QtGui -IC:/Qt/5.15.0/wasm_32/include/QtCore -I. ..\calculator\button.h -o moc_button.cpp

moc_calculator.cpp: ..\calculator\calculator.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\QWidget \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qwidget.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtguiglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtcore-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsystemdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qprocessordetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtypeinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsysinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlogging.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qflags.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbasicatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qgenericatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobalstatic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmutex.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnumeric.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qversiontagging.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtgui-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgets-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnamespace.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs_win.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstring.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qchar.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrefcount.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qarraydata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringliteral.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringview.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringbuilder.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiterator.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhashfunctions.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpair.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvector.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainertools_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpoint.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearraylist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qregexp.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringmatcher.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcoreevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qscopedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmetatype.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmargins.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpaintdevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrect.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsize.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpalette.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcolor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgb.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgba64.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qbrush.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qmatrix.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpolygon.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qregion.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdatastream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiodevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qline.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtransform.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qimage.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixelformat.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qshareddata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhash.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfont.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontmetrics.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qsizepolicy.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcursor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qkeysequence.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvariant.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdebug.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtextstream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlocale.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qset.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontiguouscache.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurlquery.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfile.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfiledevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qvector2d.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtouchdevice.h \
		moc_predefs.h \
		C:\Qt\5.15.0\wasm_32\bin\moc.exe
	C:\Qt\5.15.0\wasm_32\bin\moc.exe $(DEFINES) --include C:/Qt/Examples/Qt-5.15.0/widgets/widgets/build-calculator-Qt_5_15_0_WebAssembly-Debug/moc_predefs.h -IC:/Qt/5.15.0/wasm_32/mkspecs/wasm-emscripten -IC:/Qt/Examples/Qt-5.15.0/widgets/widgets/calculator -IC:/Qt/5.15.0/wasm_32/include -IC:/Qt/5.15.0/wasm_32/include/QtWidgets -IC:/Qt/5.15.0/wasm_32/include/QtGui -IC:/Qt/5.15.0/wasm_32/include/QtCore -I. ..\calculator\calculator.h -o moc_calculator.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

button.obj: ..\calculator\button.cpp ..\calculator\button.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\QToolButton \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtoolbutton.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtguiglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtcore-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsystemdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qprocessordetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtypeinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsysinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlogging.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qflags.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbasicatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qgenericatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobalstatic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmutex.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnumeric.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qversiontagging.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtgui-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgets-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qabstractbutton.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qicon.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsize.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnamespace.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmargins.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiterator.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrefcount.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qarraydata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhashfunctions.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstring.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qchar.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringliteral.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringview.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringbuilder.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpair.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvector.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainertools_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpoint.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearraylist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qregexp.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringmatcher.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpaintdevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs_win.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrect.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcolor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgb.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgba64.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qshareddata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhash.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcoreevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qscopedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmetatype.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qimage.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixelformat.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtransform.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qmatrix.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpolygon.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qregion.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdatastream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiodevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qline.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qkeysequence.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qwidget.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpalette.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qbrush.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfont.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontmetrics.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qsizepolicy.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcursor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvariant.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdebug.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtextstream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlocale.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qset.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontiguouscache.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurlquery.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfile.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfiledevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qvector2d.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtouchdevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o button.obj ..\calculator\button.cpp

calculator.obj: ..\calculator\calculator.cpp ..\calculator\calculator.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\QWidget \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qwidget.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtguiglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtcore-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsystemdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qprocessordetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtypeinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsysinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlogging.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qflags.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbasicatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qgenericatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobalstatic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmutex.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnumeric.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qversiontagging.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtgui-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgets-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnamespace.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs_win.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstring.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qchar.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrefcount.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qarraydata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringliteral.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringview.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringbuilder.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiterator.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhashfunctions.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpair.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvector.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainertools_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpoint.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearraylist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qregexp.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringmatcher.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcoreevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qscopedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmetatype.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmargins.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpaintdevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrect.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsize.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpalette.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcolor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgb.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgba64.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qbrush.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qmatrix.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpolygon.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qregion.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdatastream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiodevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qline.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtransform.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qimage.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixelformat.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qshareddata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhash.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfont.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontmetrics.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qsizepolicy.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcursor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qkeysequence.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvariant.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdebug.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtextstream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlocale.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qset.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontiguouscache.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurlquery.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfile.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfiledevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qvector2d.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtouchdevice.h \
		..\calculator\button.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\QToolButton \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtoolbutton.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qabstractbutton.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qicon.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\QGridLayout \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qgridlayout.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qlayout.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qlayoutitem.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qboxlayout.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\QLineEdit \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qlineedit.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qframe.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtextcursor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtextformat.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpen.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtextoption.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\QtMath \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculator.obj ..\calculator\calculator.cpp

main.obj: ..\calculator\main.cpp C:\Qt\5.15.0\wasm_32\include\QtWidgets\QApplication \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qapplication.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgetsglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtguiglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobal.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig-bootstrapped.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qconfig.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtcore-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsystemdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qprocessordetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcompilerdetection.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtypeinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsysinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlogging.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qflags.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbasicatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_bootstrap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qgenericatomic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_cxx11.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qatomic_msvc.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qglobalstatic.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmutex.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnumeric.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qversiontagging.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtgui-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qtwidgets-config.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcoreapplication.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstring.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qchar.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrefcount.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qnamespace.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qarraydata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringliteral.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringview.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringbuilder.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobjectdefs_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qalgorithms.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiterator.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhashfunctions.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpair.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvector.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainertools_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qpoint.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qbytearraylist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringlist.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qregexp.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qstringmatcher.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcoreevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qscopedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmetatype.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvarlengtharray.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontainerfwd.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qobject_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qeventloop.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qwindowdefs_win.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsize.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmargins.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcursor.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qdesktopwidget.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qwidget.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpaintdevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qrect.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpalette.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qcolor.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgb.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qrgba64.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qbrush.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qmatrix.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpolygon.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qregion.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdatastream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qiodevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qline.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtransform.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qimage.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixelformat.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qpixmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qshareddata.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qhash.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qsharedpointer_impl.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfont.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontmetrics.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qfontinfo.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\qsizepolicy.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qkeysequence.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qevent.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qvariant.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qmap.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qdebug.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qtextstream.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qlocale.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qset.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qcontiguouscache.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurl.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qurlquery.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfile.h \
		C:\Qt\5.15.0\wasm_32\include\QtCore\qfiledevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qvector2d.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qtouchdevice.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qguiapplication.h \
		C:\Qt\5.15.0\wasm_32\include\QtGui\qinputmethod.h \
		..\calculator\calculator.h \
		C:\Qt\5.15.0\wasm_32\include\QtWidgets\QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj ..\calculator\main.cpp

calculator.js_plugin_import.obj: C:/Qt/Examples/Qt-5.15.0/widgets/widgets/build-calculator-Qt_5_15_0_WebAssembly-Debug/calculator.js_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculator.js_plugin_import.obj C:/Qt/Examples/Qt-5.15.0/widgets/widgets/build-calculator-Qt_5_15_0_WebAssembly-Debug/calculator.js_plugin_import.cpp

moc_button.obj: moc_button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_button.obj moc_button.cpp

moc_calculator.obj: moc_calculator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calculator.obj moc_calculator.cpp

####### Install

install_target: first FORCE
	@if not exist C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator mkdir C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator & if not exist C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator exit 1
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator\$(QMAKE_TARGET)
	-$(DEL_DIR) C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator 


install_js_file: first FORCE
	@if not exist C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator mkdir C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator & if not exist C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator exit 1
	$(QINSTALL_PROGRAM) C:\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator\calculator.js C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator\calculator.js

uninstall_js_file: FORCE
	-$(DEL_FILE) C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator\calculator.js
	-$(DEL_DIR) C:$(INSTALL_ROOT:@msyshack@%=%)\Qt\Examples\Qt-5.15.0\widgets\widgets\calculator 


install: install_target install_js_file  FORCE

uninstall: uninstall_target uninstall_js_file  FORCE

FORCE:

